INSERT INTO DESCRIZIONE(ID, COMANDO, STANZA, STATO, OGGETTO, DESCRIZIONE) VALUES
(1, '0', 'Stanza1', 'true', '0', 'Una notte di pioggia, la tua auto si spegne nel nulla. Il navigatore, prima di morire, mormora: "Calcolando la tua fine...". In lontananza, una villa antica si staglia sulla collina, illuminata dai fulmini e immersa in un odore stantio che sa di muffa e mistero. Ti rifugi all''interno. Il portone si chiude alle tue spalle con un colpo secco. Il silenzio cala. La casa sembra osservarti. E non ha alcuna intenzione di lasciarti andare.'),
(2, 'Osserva', 'Stanza1', 'true', '0', 'Sei nell''ingresso della casa. L''aria è fredda e immobile, e ogni passo fa scricchiolare il pavimento sotto i tuoi piedi. Un tavolino impolverato cattura la tua attenzione.'),
(3, 'Osserva', 'Stanza1', 'true', 'Tavolo', 'Un tavolino su cui giacciono una candela e un foglio piegato, ricoperto da un velo di cenere sottile.'),
(4, 'Prendi', 'Stanza1', 'true', 'Candela', 'Hai preso la Candela. Emette una fiamma debole ma costante.'),
(5, 'Usa', 'Stanza1', 'true', 'Fiammiferi', 'Hai accesso la candela. La stanza è leggermente più illuminata.'),
(6, 'Osserva', '0', 'true', '0', 'Fiammiferi', 'Una scatola di fiammiferi secchi.'),
(7, 'Osserva', 'Stanza1', 'true', 'Foglio', 'Verso nord, la luce trova ciò che l''ombra nasconde.'),
(8, 'Osserva', 'Stanza2', 'true', '0', 'Entri in un salone ampio e silenzioso. La luce della candela tremola sulle pareti annerite dal fumo. Un grande camino domina la stanza: la cenere al suo interno è fredda, ma qualcosa brilla tra le ombre. Sul pavimento, un tappeto consunto emana un odore di muffa e copre parte delle assi scricchiolanti.'),
(9, 'Osserva', 'Stanza2', 'true', 'Camino', 'Sopra il camino, tra la polvere e la fuliggine, noti una vecchia chiave di ferro che riflette la luce della candela.'),
(10, 'Prendi', 'Stanza2', 'true', 'Chiave', 'Hai raccolto la vecchia Chiave di ferro.'),
(11, 'Osserva', 'Stanza2', 'true', 'Tappeto', 'Un vecchio tappeto logoro, pieno di macchie di cera e bruciature. Uno scrigno antico si trova proprio sul tappeto.'),
(12, 'Osserva', 'Stanza2', 'true', 'Scrigno', 'Uno scrigno antico, con una serratura arrugginita. Sembra poter essere aperto con la chiave trovata sul camino. All''interno troverai un amuleto d''argento a forma di goccia.'),
(13, 'Usa', 'Stanza2', 'true', 'Chiave', 'Hai inserito la Chiave arrugginita nello Scrigno e hai sentito un click. Lo scrigno è ora aperto.'),
(14, 'Prendi', 'Stanza2', 'true', 'Amuleto', 'Hai preso l''Amuleto d''argento. Senti un leggero calore emanare da esso.'),
(15, 'Osserva', 'Stanza3', 'true', '0', 'La porta si apre su una piccola biblioteca. L''odore di carta bruciata e muffa ti avvolge. Gli scaffali sono piegati dal peso dei volumi anneriti. Solo uno sembra intatto, come se qualcuno lo avesse protetto dal tempo.'),
(16, 'Osserva', 'Stanza3', 'true', 'Scaffale', 'Tra i libri carbonizzati, un diario attira la tua attenzione: la copertina è intatta, di cuoio nero, con un simbolo inciso.'),
(17, 'Prendi', 'Stanza3', 'true', 'Diario', 'Hai preso il Diario. Le pagine sono intatte nonostante tutto.'),
(18, 'Osserva', 'Stanza3', 'true', 'Diario', 'Sfogli alcune pagine: sono piene di appunti e simboli. Parla di un rituale per riportare la casa alla pace, e cita tre oggetti sacri: luce, protezione e memoria.'),
(19, 'Osserva', 'Stanza4', 'true', '0', 'Appena entri, vieni avvolto da un silenzio irreale. Le pareti sono completamente ricoperte di specchi antichi, incrinati in più punti, che riflettono la luce tremolante della candela moltiplicando la tua immagine all''infinito. All''improvviso, senti il telefono vibrare nel taschino.'),
(20, 'Osserva', '0', 'true', 'Telefono', 'Il tuo cellulare, pronto per essere usato. Forse il segnale è tornato?'),
(21, 'Usa', 'Stanza4', 'true', 'Telefono', 'Hai attivato l''enigma dello specchio.'),
(22, '0', 'Stanza4', 'Corretto', '0', 'Risposta corretta.'),
(23, '0', 'Stanza4', 'Sbagliato', '0', 'Risposta errata.'),
(24, 'Osserva', 'Stanza5', 'true', '0', 'Una fredda penombra avvolge la cripta. Davanti a te si erge un altare di pietra decorato con simboli identici a quelli trovati nelle stanze precedenti.'),
(25, 'Osserva', 'Stanza5', 'true', 'Altare', 'Un altare su cui vi e'' un''iscrizione incisa che recita: "Riporta la luce, la memoria e la protezione. Solo allora la casa avra'' pace."'),
(26, 'Lascia', 'Stanza5', 'true', 'Candela', ''),
(27, 'Lascia', 'Stanza5', 'true', 'Amuleto', ''),
(28, 'Lascia', 'Stanza5', 'true', 'Diario', '');
